# Linear algebra basics

This notebook provides in introduction to essential elements of linear algebra needed to understand the dimensionality reduction algorithms performed by *flowTorch*.

## Multiplication
### Matrix-vector multiplication
### Matrix-matrix multiplication

## Special types of matrices
### Identity matrix
### Orthogonal matrix
### Orthonormal matrix
### Unitary matrix

## Eigen-decomposition
### ...
### Application to linear operators

## Singular value decomposition
### ...
### Low-rank approximation
### Least-squares approximation
### Connection so Eigen-decomposition

In [56]:
import numpy as np

A= np.array([[3, -5, 3],
            
            [7,9,3],
            
            [2,6,4]])

B= np.array([2, 2, 9])

c=A*B

print(c)

[[  6 -10  27]
 [ 14  18  27]
 [  4  12  36]]
